/* Create a vehicle class function, which can be used to create vehicle objects by given parameters. The 
vehicle objects should have the following properties - example values:
    type – truck(string)
    tireCount – 6(number)
    capacity – 5 (number)    
   */

/* Create a loop which creates 10 vehicle objects with random values for the properties.
   Random values can be generated by using the Math.random() function.
   The loop should store the created vehicle objects in an array */

/* Create a function which accepts an array of vehicles as a parameter and 
   prints the types of the vehicles to the console */
